### ISSUE TITLE
TOSVersion.TArchitecture compile error in Delphi 10.1 Berlin

### ISSUE THREAD

**Issue by jonjbar** [tondrej/chakracore-delphi#1]
https://github.com/tondrej/chakracore-delphi/blob/57a4c4328c2ba42ec353da04516cfa353e6b276d/src/Compat.pas#L178

This line should be:

`ArchitectureStrings: array[TOSVersion.TArchitecture] of string = ('x86', 'x64', 'arm32'{$ifdef DELPHIX_BERLIN_UP}, 'arm64'{$endif});`

**Comment by tondrej** [comment]
Done. Thanks!
