### ISSUE TITLE
Tests/Samples fail to compile - JsDeleteProperty not marked with overload

### ISSUE THREAD

**Issue by darianmiller** [tondrej/chakracore-delphi#13]
Adding the function overloads to the interface portion seems to correct it:

function JsDeleteProperty(Value, Prop: JsValueRef; UseStrictRules: Boolean): Boolean; overload;
function JsDeleteProperty(Value: JsValueRef; PropId: JsPropertyIdRef; UseStrictRules: Boolean): Boolean; overload;
function JsDeleteProperty(Value: JsValueRef; const PropName: UTF8String; UseStrictRules: Boolean): Boolean; overload;
function JsDeleteProperty(Value: JsValueRef; const PropName: UnicodeString; UseStrictRules: Boolean): Boolean; overload;

**Comment by tondrej** [comment]
Thanks.
