### ISSUE TITLE
NodeSample.Tokyo.dproj project doesn't build - missing Console unit

### ISSUE THREAD

**Issue by darianmiller** [tondrej/chakracore-delphi#14]
NodeSample.Tokyo.dproj is a bit hosed - won't build due to missing icons, but also doesn't include the Console unit

**Comment by tondrej** [comment]
Thanks. Until I get around to fixing it for Tokyo:

The Console unit is [there](https://github.com/tondrej/chakracore-delphi/blob/master/samples/HostSample/Console.pas), just add it to your search path.
The icon can be fixed in the project options (load the default icon or whatever icon you like).
