### ISSUE TITLE
Missing chakracore.dll with vindows 10/11

### ISSUE THREAD

**Issue by bnzbnz** [tondrej/chakracore-delphi#18]
- Missing chakracore.dll on vindows 10/11 built with Delphi 11 Alexandia
- Jedi.inc missing from the distribution

Thank you

**Comment by tondrej** [comment]
As mentioned in the [readme](https://github.com/tondrej/chakracore-delphi#readme) you can download chakracore.dll from their [release](https://github.com/Microsoft/ChakraCore/releases/tag/v1.11.24) page.
jedi.inc submodule is not missing if you follow the instructions in the readme.
