### ISSUE TITLE
Exception of new object in multithreading

### ISSUE THREAD

**Issue by pony5551** [tondrej/chakracore-delphi#5]
I uploaded a file!

[ThreadDemo.zip](https://github.com/tondrej/chakracore-delphi/files/2994522/ThreadDemo.zip)

![6](https://user-images.githubusercontent.com/36391163/54794321-d0dac080-4c81-11e9-8ee6-c24d5e8aa969.png)

{$DEFINE SScript2} is normal!

**Comment by tondrej** [comment]
I can confirm an access violation. Thanks for finding this, I'll post a new issue with a MCVE as there's too much unrelated code in your example. The issue can be reproduced regardless of multi-threading.

BTW this code is wrong:
`RegisterMethod(AInstance, 'free', @TConsole.Free);`

Any method you wish to register as a native callback must have the specific signature:
`function(Args: PJsValueRef; ArgCount: Word): JsValueRef of object;`

(as [shown](https://github.com/tondrej/chakracore-delphi/blob/48bea5871e748e2d085550aca4ac1327c1908210/samples/HostSample/Console.pas#L239) in the `TConsole` example).

I should probably make it clear in a comment or wiki.

**Comment by pony5551** [comment]
Sorry, I used it wrong

RegisterMethod (AInstance, 'free' @ TConsole. Free);

**Comment by tondrej** [comment]
> Sorry, I used it wrong
> 
> RegisterMethod (AInstance, 'free' @ TConsole. Free);

No problem, and thanks for reporting.

**Comment by tondrej** [comment]
Constructors of projected classes must be addref-ed to prevent them from being garbage-collected.
Thank you for finding and reporting it.

**Comment by tondrej** [comment]
See [TestFinalizer4](https://github.com/tondrej/chakracore-delphi/blob/51f5ce6ddb919f3117d0296bf81103ca50bb97c8/tests/Test_Classes.pas#L843) for a minimal example to reproduce the problem: simply call the script in a loop long enough until GC releases the constructor - . The next attempt to call the constructor will cause an access violation.

**Comment by pony5551** [comment]
You may have to submit an issue to chakracore using c++

**Comment by tondrej** [comment]
Sorry for being unclear. The issue was on the chakracore-delphi side (Pascal), and it's [fixed](https://github.com/tondrej/chakracore-delphi/commit/51f5ce6ddb919f3117d0296bf81103ca50bb97c8) now.

**Comment by pony5551** [comment]
I see！thank you！

**Comment by tondrej** [comment]
Welcome and thank you for your help.
