### ISSUE TITLE
nodesample 

### ISSUE THREAD

**Issue by pony5551** [tondrej/chakracore-delphi#7]
Please give a sample script of nodesample.exe.
nodesample.exe demo_lodash.js
I'm going to use that to prompt:

---------------------------
Debugger Exception Notification
---------------------------
Project NodeSample.exe raised exception class Exception with message 'Module 'lodash' not found'.
---------------------------
Break   Continue   Help   
---------------------------

**Comment by tondrej** [comment]
You can install it with `npm install lodash` within the `NodeSample` directory - see my [blog post](https://tondrej.blogspot.com/2019/01/node-modules-with-delphi-and-free-pascal.html) with [video](https://youtu.be/E_MAiTIzEz8).
