### ISSUE TITLE
How to operate JsNumberToInt64?!

### ISSUE THREAD

**Issue by pony5551** [tondrej/chakracore-delphi#9]
to int64
to Cardinal

and 
int64 to JsNumber
.....

**Comment by pony5551** [comment]
use
 JsNumberToDouble
 DoubleToJsNumber

??

**Comment by tondrej** [comment]
Yes - for now you can use the APIs exposed by ChakraCore:

- [`JsDoubleToNumber`](https://github.com/tondrej/chakracore-delphi/blob/9f9f3593cf554b87dc235fa27940dab00cf5845f/src/ChakraCommon.pas#L1229)
- [`JsIntToNumber`](https://github.com/tondrej/chakracore-delphi/blob/9f9f3593cf554b87dc235fa27940dab00cf5845f/src/ChakraCommon.pas#L1244)
- [`JsNumberToDouble`](https://github.com/tondrej/chakracore-delphi/blob/9f9f3593cf554b87dc235fa27940dab00cf5845f/src/ChakraCommon.pas#L1260)
- [`JsNumberToInt`](https://github.com/tondrej/chakracore-delphi/blob/9f9f3593cf554b87dc235fa27940dab00cf5845f/src/ChakraCommon.pas#L1276)

or the corresponding helpers in ChakraCoreUtils:

- [`DoubleToJsNumber`](https://github.com/tondrej/chakracore-delphi/blob/27628b7bea5964d19fea19aa30dc15c6a09e87c1/src/ChakraCoreUtils.pas#L74)
- [`IntToJsNumber`](https://github.com/tondrej/chakracore-delphi/blob/27628b7bea5964d19fea19aa30dc15c6a09e87c1/src/ChakraCoreUtils.pas#L75)
- [`JsNumberToDouble`](https://github.com/tondrej/chakracore-delphi/blob/27628b7bea5964d19fea19aa30dc15c6a09e87c1/src/ChakraCoreUtils.pas#L94)
- [`JsNumberToInt`](https://github.com/tondrej/chakracore-delphi/blob/27628b7bea5964d19fea19aa30dc15c6a09e87c1/src/ChakraCoreUtils.pas#L95)

[Int64 support seems to be coming](https://github.com/Microsoft/ChakraCore/pull/4827) in one of the future releases.

**Comment by pony5551** [comment]
thanks
